modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/CreativeMD/ItemPhysic/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="itemphysic"
    logoFile="itemphysic.png"
    version="1.8.0"
    displayName="ItemPhysic"
    displayURL="https://modrinth.com/mod/itemphysic"
    authors="CreativeMD"
    description='''Enhances the rendering of items and introduces some more physics.'''

[[dependencies.itemphysic]]
    modId="neoforge"
    type="required"
    versionRange="[21.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemphysic]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemphysic]]
   modId="creativecore"
   type="required"
   ordering="NONE"
   side="BOTH"
   versionRange="[2.12.0,)"

[[mixins]]
   config="itemphysic.mixins.json"

